- id: '1691601978106'
  alias: 'Wireless Scene Switch Button 1: Single Click'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: cb29a302c231889a9230b2721ef293c6
    type: action
    subtype: 1_single
    discovery_id: 0x847127fffee7a266 action_1_single
  condition: []
  action:
  - type: toggle
    device_id: fe21a17957d306d103a331a934918d42
    entity_id: f144fb4f134d9366cb15fb857796768c
    domain: switch
  mode: single
- id: '1687986581799'
  alias: 'Wireless Scene Switch Button 1: Double Click'
  description: Turn on devices in Office
  trigger:
  - platform: device
    domain: mqtt
    device_id: cb29a302c231889a9230b2721ef293c6
    type: action
    subtype: 1_double
    discovery_id: 0x847127fffee7a266 action_1_double
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.start_work
    metadata: {}
  mode: single
- id: '1687903120479'
  alias: 'Wireless Scene Switch Button 1: Hold'
  description: Turn off all devices in Office
  trigger:
  - platform: device
    domain: mqtt
    device_id: cb29a302c231889a9230b2721ef293c6
    type: action
    subtype: 1_hold
    discovery_id: 0x847127fffee7a266 action_1_hold
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.leave_workspace
    metadata: {}
  mode: single
- id: '1687987105333'
  alias: 'Wireless Scene Switch Button 2: Single Click'
  description: Toggle Color Strip Light
  trigger:
  - platform: device
    domain: mqtt
    device_id: cb29a302c231889a9230b2721ef293c6
    type: action
    subtype: 2_single
    discovery_id: 0x847127fffee7a266 action_2_single
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_off
        device_id: 2c21cd3b125bca6dc285096fb7076ef8
        entity_id: b6e5db59ae91bfe8cd001c5d476a12c3
        domain: light
      sequence:
      - type: turn_on
        device_id: 2c21cd3b125bca6dc285096fb7076ef8
        entity_id: b6e5db59ae91bfe8cd001c5d476a12c3
        domain: light
      - type: turn_on
        device_id: 6ee7f9569927e68779688453712a062f
        entity_id: 2b56ccd2dee1b22ab8d4c58207a52ccd
        domain: light
      - type: turn_on
        device_id: aeb01ddad29791c65fa07d1adccf99b3
        entity_id: 3beb3f18675dcb8da97c13a9939733da
        domain: switch
    - conditions:
      - condition: device
        type: is_on
        device_id: 2c21cd3b125bca6dc285096fb7076ef8
        entity_id: b6e5db59ae91bfe8cd001c5d476a12c3
        domain: light
      sequence:
      - type: turn_off
        device_id: 2c21cd3b125bca6dc285096fb7076ef8
        entity_id: b6e5db59ae91bfe8cd001c5d476a12c3
        domain: light
      - type: turn_off
        device_id: 6ee7f9569927e68779688453712a062f
        entity_id: 2b56ccd2dee1b22ab8d4c58207a52ccd
        domain: light
      - type: turn_off
        device_id: aeb01ddad29791c65fa07d1adccf99b3
        entity_id: 3beb3f18675dcb8da97c13a9939733da
        domain: switch
  mode: single
- id: '1691696329240'
  alias: 'Wireless Scene Switch Button 3: Single Click'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: cb29a302c231889a9230b2721ef293c6
    type: action
    subtype: 3_single
    discovery_id: 0x847127fffee7a266 action_3_single
  condition: []
  action:
  - type: toggle
    device_id: aeb01ddad29791c65fa07d1adccf99b3
    entity_id: c0ce6c99d98b754b30ac3740c6c00528
    domain: switch
  mode: single
- id: '1691696329240'
  alias: 'Wireless Scene Switch Button 3: Single Click'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: cb29a302c231889a9230b2721ef293c6
    type: action
    subtype: 3_single
    discovery_id: 0x847127fffee7a266 action_3_single
  condition: []
  action:
  - type: toggle
    device_id: aeb01ddad29791c65fa07d1adccf99b3
    entity_id: c0ce6c99d98b754b30ac3740c6c00528
    domain: switch
  mode: single
- id: '1688047602778'
  alias: 'Wireless Scene Switch Button 3: Double Click'
  description: Turn Off Some Devices for Movie Mode
  trigger:
  - platform: device
    domain: mqtt
    device_id: cb29a302c231889a9230b2721ef293c6
    type: action
    subtype: 3_double
    discovery_id: 0x847127fffee7a266 action_3_double
  condition: []
  action:
  - type: turn_off
    device_id: fe21a17957d306d103a331a934918d42
    entity_id: 82a3aaf1c8f911b8ad2fcaf9209b3cd9
    domain: light
  - type: turn_off
    device_id: 2c21cd3b125bca6dc285096fb7076ef8
    entity_id: light.rgbcw_dream_color_strip_light
    domain: light
  - type: turn_off
    device_id: 6ee7f9569927e68779688453712a062f
    entity_id: light.dream_color_strip_neon_light
    domain: light
  - type: turn_off
    device_id: c46fb495627262b868b9e09950936262
    entity_id: switch.billy_bookcase_breaker_switch
    domain: switch
  - type: turn_off
    device_id: aeb01ddad29791c65fa07d1adccf99b3
    entity_id: c0ce6c99d98b754b30ac3740c6c00528
    domain: switch
  - type: turn_off
    device_id: aeb01ddad29791c65fa07d1adccf99b3
    entity_id: 3beb3f18675dcb8da97c13a9939733da
    domain: switch
  mode: single
- id: '1691696413402'
  alias: 'Wireless Scene Switch Button 4: Single Click'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: cb29a302c231889a9230b2721ef293c6
    type: action
    subtype: 4_single
    discovery_id: 0x847127fffee7a266 action_4_single
  condition: []
  action:
  - type: toggle
    device_id: c46fb495627262b868b9e09950936262
    entity_id: 51e71e8fe0c14a53a0149f39c933ba3a
    domain: switch
  mode: single
- id: '1695043099374'
  alias: NSPanel Configuration
  description: ''
  use_blueprint:
    path: Blackymas/nspanel_blueprint.yaml
    input:
      nspanel_name: a1ecf0ef1b5813c1b25bced6ee215388
      date_format: '%A, %d/%m'
      weather_entity: weather.forecast_sweet_home_jp
      indoortemp: sensor.zhimi_mb3_fe5b_temperature_2
      chip01: binary_sensor.dscalarm_z01_front_door
      chip01_icon: mdi:door-sliding-open
      chip02_icon: mdi:window-open-variant
      chip04_icon: mdi:door-sliding-open
      chip02: binary_sensor.dscalarm_z02_living_window
      chip03: binary_sensor.dscalarm_z03_dining_door_window
      chip03_icon: mdi:door-sliding-open
      chip04: binary_sensor.dscalarm_z04_kitchen_door
      chip05: binary_sensor.dscalarm_z05_bathroom_window
      chip05_icon: mdi:window-open
      alarm: alarm_control_panel.safe_alarm_panel
      climate: climate.mitsubishi_electric_1stfloor
      climate_value01: sensor.zhimi_mb3_fe5b_relative_humidity_2
      climate_value01_icon: mdi:water-percent
      climate_value02: sensor.zhimi_mb3_fe5b_pm25_2
      climate_value02_icon: mdi:air-filter
      qrcode_value: WIFI:S:Sweet Home JP;T:WPA;P:1212312121;H:false;;
      qrcode_label: WiFi
      left_button_name: Living
      left_button_entity: switch.nspanel_usw_relay_2
      right_button_entity: switch.nspanel_usw_relay_1
      right_button_name: Dinning
      right_button_hold_select: Default
      entity01: scene.go_upstairs
      entity02: scene.start_work
      entity02_confirm: true
      entity01_confirm: true
      entity01_name: Go Upstairs
      entity02_name: Enter Workspace
      entity02_icon: mdi:desk-lamp
      entity01_icon: mdi:stairs-up
      entity03: scene.leave_workspace
      entity03_name: Leave Workspace
      entity03_icon: mdi:desk-lamp-off
      entity04: light.garage_switch_l1
      entity04_name: Garage
      entity04_icon: mdi:garage
- id: '1695044261557'
  alias: Toggle Automation Micro Switch
  description: ''
  trigger:
  - type: temperature
    platform: device
    device_id: d38f58bcea4cc4ef10c6ecadc34ec3f7
    entity_id: 164fcaeee32158fb2222148dc74373ef
    domain: sensor
    above: 35
    below: 30
  condition: []
  action:
  - choose:
    - conditions:
      - type: is_temperature
        condition: device
        device_id: d38f58bcea4cc4ef10c6ecadc34ec3f7
        entity_id: 164fcaeee32158fb2222148dc74373ef
        domain: sensor
        above: 35
      sequence:
      - type: turn_on
        device_id: 2db33914b4942e53a9c190cb1bc053c3
        entity_id: 8a475f6b3e0b3b7f5eca33bc7a4a6a26
        domain: switch
    - conditions:
      - type: is_temperature
        condition: device
        device_id: d38f58bcea4cc4ef10c6ecadc34ec3f7
        entity_id: 164fcaeee32158fb2222148dc74373ef
        domain: sensor
        below: 30
      sequence:
      - type: turn_off
        device_id: 2db33914b4942e53a9c190cb1bc053c3
        entity_id: 8a475f6b3e0b3b7f5eca33bc7a4a6a26
        domain: switch
  mode: single
- id: '1695044323631'
  alias: Link Multiple Switches - Garage Switch
  description: ''
  use_blueprint:
    path: chettapong/link_multiple_switches.yaml
    input:
      switches:
      - switch.garage_switch_l1
      - switch.1st_floor_wall_lamp_garage_fence_lamp_switch_center
- id: '1695044364449'
  alias: Link Multiple Switches - Stair Switch
  description: ''
  use_blueprint:
    path: chettapong/link_multiple_switches.yaml
    input:
      switches:
      - switch.stairs_switch
      - switch.1st_floor_stairs_kitchen_back_door_switch_l1
- id: '1695044385448'
  alias: Link Multiple Switches - Side Yard Switch
  description: ''
  use_blueprint:
    path: chettapong/link_multiple_switches.yaml
    input:
      switches:
      - switch.side_yard_light_switch_1_433_switch
      - switch.garage_switch_l2
- id: '1695044440851'
  alias: Link Multiple Switches - Living Switch
  description: ''
  use_blueprint:
    path: chettapong/link_multiple_switches.yaml
    input:
      switches:
      - switch.1st_floor_living_front_door_switch_left
      - switch.nspanel_usw_relay_2
- id: '1695044484682'
  alias: Update Map Extractor camera
  description: ''
  use_blueprint:
    path: PiotrMachowski/update_map_extractor.yaml
    input:
      vacuum: vacuum.roidmi_v60_fa52_robot_cleaner
      camera: camera.roidmi_eve
      mode_to_handle: default_when_cleaning
- id: '1695044589805'
  alias: Storage Room Door Contact Sensor
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 1db7777bdad5ae983a079f454f1a7e28
    entity_id: a4651ec910e5a434eca6e4293df48e6e
    domain: binary_sensor
  - type: not_opened
    platform: device
    device_id: 1db7777bdad5ae983a079f454f1a7e28
    entity_id: a4651ec910e5a434eca6e4293df48e6e
    domain: binary_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - type: is_open
        condition: device
        device_id: 1db7777bdad5ae983a079f454f1a7e28
        entity_id: a4651ec910e5a434eca6e4293df48e6e
        domain: binary_sensor
      sequence:
      - type: turn_on
        device_id: 8151eb2acd9aae8c4a51153b41f511c8
        entity_id: aaebdf43be297517042c466dadf10958
        domain: light
    - conditions:
      - type: is_not_open
        condition: device
        device_id: 1db7777bdad5ae983a079f454f1a7e28
        entity_id: a4651ec910e5a434eca6e4293df48e6e
        domain: binary_sensor
      sequence:
      - type: turn_off
        device_id: 8151eb2acd9aae8c4a51153b41f511c8
        entity_id: aaebdf43be297517042c466dadf10958
        domain: light
  mode: single
- id: '1695044707208'
  alias: Turn off device at 7.00 am
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - parallel:
    - type: turn_off
      device_id: f3a0f16271e1f694b713f92fc26bd6aa
      entity_id: 258037188097d5d3f791440d9b5396f1
      domain: light
    - type: turn_off
      device_id: 8c149041ca56a72c0a3a7795196ff5b0
      entity_id: 207e35fbb50e1000fd421385907ae286
      domain: light
    - type: turn_off
      device_id: a798ce9b53a6c4ea51ca73a3eb7eb842
      entity_id: 518ad641f3fa0c992c555f88ff034030
      domain: light
    - type: turn_off
      device_id: fc9233a09eda558fa6dc10f2e1dd23e4
      entity_id: 52510be54f9b11f75a65b53cce948b7e
      domain: light
    - type: turn_off
      device_id: ea85dc1d24076f33df5f973e3431c767
      entity_id: 6a96632213cf17cb883e1191707b5127
      domain: switch
  mode: single
