# Setup basic information
# See https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Sweet Home JP
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  currency: THB
  country: TH
  time_zone: "Asia/Bangkok"
  external_url: !secret homeassistant_external_url
  packages: !include_dir_named packages

# HTTP
# See https://www.home-assistant.io/integrations/http/#configuration-variables
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Loads default set of integrations. Do not remove.
default_config:

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

##############################################
################ UI Libraries ################
##############################################

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards:
    # Main Dashboard
    lovelace-dashboard:
      mode: yaml
      title: Dashboard
      icon: mdi:monitor
      show_in_sidebar: true
      filename: lovelace/dashboards/dashboard.yaml

    # Rooms + Areas
    lovelace-rooms:
      mode: yaml
      title: Rooms
      icon: mdi:sofa
      show_in_sidebar: true
      require_admin: false
      filename: lovelace/dashboards/rooms.yaml

#################################################################
## Components
#################################################################

# Google Assistant integration
# See https://www.home-assistant.io/integrations/google_assistant/#configuration-variables
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  expose_by_default: false
  entity_config:
    ## Alarm control panel
    # alarm_control_panel.dsc_alarm:
    #   name:

    # Camera
    camera.nvt_mainstream:
      name: กล้องหน้าบ้าน
      aliases:
        - Front house camera
    camera.ipc_03_profile_000:
      name: กล้องข้างบ้าน
      aliases:
        - Side house camera
    camera.ipc_04_profile_000:
      name: กล้องหลังบ้าน
      aliases:
        - Back yard camera
    camera.ipc_05_mainstream:
      name: กล้องห้องครัว
      aliases:
        - Kitchen room camera

    ## Climate
    climate.mitsubishi_electric_1stfloor:
      name: แอร์ชั้นล่าง
    climate.mitsubishi_electric_workspace:
      name: แอร์ห้องทำงาน
    # climate.mitsubishi_electric_bedroom:
    #   name: แอร์ห้องนอนเล็ก

    # Fan
    fan.dmaker_p9_1cbb_fan:
      name: พัดลม
      aliases:
        - พัดลมห้องนอน
        - Tower fan
    fan.zhimi_za5_beba_fan:
      name: พัดลม
      aliases:
        - พัดลมห้องทำงาน
        - Standing fan

    ## Light
    light.front_house_switch_left:
      name: โคมไฟกิ่งหน้าบ้าน
      aliases:
        - Front Wall Light
    light.front_house_switch_right:
      name: ไฟประตูรั้ว
      aliases:
        - Fence Gate Light
    light.garage_switch_l1:
      name: ไฟหลังคาจอดรถ
      aliases:
        - Garage Light
    light.living_front_door_switch_left:
      name: ไฟหน้าทีวี
      aliases:
        - Living light
        - TV light
    light.living_front_door_switch_right:
      name: ไฟประตูหน้าบ้าน
      aliases:
        - Front Door Light
    light.dining_switch:
      name: ไฟโต๊ะกินข้าว
      aliases:
        - ไฟโต๊ะทานข้าว
        - Dining Light
    light.stair_switch:
      name: ไฟบันได
      aliases:
        - Stair Light
    light.kitchen_stair_backdoor_center:
      name: ไฟห้องครัว
      aliases:
        - Kitchen light
    light.kitchen_stair_backdoor_right:
      name: ไฟหลังบ้าน
      aliases:
        - Backdoor Light
    light.workspace_light:
      name: ไฟห้องทำงาน
      aliases:
        - Workspace light
    light.nspanel_usw_relay_1:
      name: ไฟโต๊ะกินข้าว
      aliases:
        - ไฟโต๊ะทานข้าว
        - Dining Light
    light.nspanel_usw_relay_2:
      aliases:
        - ไฟหน้าทีวี
    light.controller_rgb_ir_cd8027:
      aliases:
        - Bed light
        - ไฟเตียง

    # Switch
    switch.smart_plug_desk:
      name: ปลั๊กไฟโต๊ะทำงาน
      aliases:
        - Desk outlet
    switch.smart_plug_ups:
      name: ปลั๊กเครื่องสำรองไฟ
      aliases:
        - UPS outlet
    switch.smart_plug_refrigerator:
      name: ปลั๊กตู้เย็น
      aliases:
        - Refrigerator outlet

    # Vacuum
    vacuum.roidmi_v60_fa52_robot_cleaner:
      name: หุ่นยนต์ดูดฝุ่น
      aliases:
        - ROIDMI EVE Robot Cleaner
        - Robot Cleaner

# AirCloud Home Assistant Integration
air_cloud:
  email: !secret air_cloud_email
  password: !secret air_cloud_password
climate:
  - platform: air_cloud

# Xiaomi Cloud Map Extractor
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "sg"
    draw: ["all"]
    name: "ROIDMI EVE"
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [0, 0, 0]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_ignored_obstacle: [0, 0, 0, 127]
      color_ignored_obstacle_with_photo: [0, 0, 0, 127]
      color_obstacle: [0, 0, 0, 127]
      color_obstacle_with_photo: [0, 0, 0, 127]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_cleaned_area: [127, 127, 127, 127]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_new_discovered_area: [64, 64, 64]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_room_names: [0, 0, 0]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    map_transformation:
      scale: 4
      trim:
        top: 35
    sizes:
      charger_radius: 24
      vacuum_radius: 24
      obstacle_radius: 12
      ignored_obstacle_radius: 12
      obstacle_with_photo_radius: 12
      ignored_obstacle_with_photo_radius: 12
      path_width: 4
    attributes:
      - calibration_points

# DSC POWERSERIES alarm system
alarm_control_panel:
  - platform: template
    panels:
      safe_alarm_panel:
        name: "Alarm Panel"
        value_template: "{{states('sensor.dscalarm_partition_1_status')}}"
        code_arm_required: false

        arm_away:
          - service: esphome.dscalarm_alarm_arm_away

        arm_home:
          - service: esphome.dscalarm_alarm_arm_home

        arm_night:
          - service: esphome.dscalarm_alarm_arm_night
            data_template:
              code: "{{code}}" #if you didnt set it in the yaml, then send the code here

        disarm:
          - service: esphome.dscalarm_alarm_disarm
            data_template:
              code: "{{code}}"
