# Setup basic information
# See https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Sweet Home JP
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  currency: THB
  country: TH
  time_zone: "Asia/Bangkok"
  external_url: !secret homeassistant_external_url
  packages: !include_dir_named packages

# HTTP
# See https://www.home-assistant.io/integrations/http/#configuration-variables
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Google Assistant integration
# See https://www.home-assistant.io/integrations/google_assistant/#configuration-variables
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - switch
    - light

# Loads default set of integrations. Do not remove.
default_config:

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards:
    # Main Dashboard
    lovelace-dashboard:
      mode: yaml
      title: Dashboard
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace/dashboards/dashboard.yaml

    # Rooms + Areas
    # lovelace-rooms:
    #   mode: yaml
    #   title: Rooms
    #   icon: mdi:sofa
    #   show_in_sidebar: true
    #   require_admin: false
    #   filename: lovelace/dashboards/rooms.yaml

# AirCloud Home Assistant Integration
air_cloud:
  email: !secret air_cloud_email
  password: !secret air_cloud_password
climate:
  - platform: air_cloud
