# Setup basic information
# See https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Sweet Home JP
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  currency: THB
  country: TH
  time_zone: "Asia/Bangkok"
  external_url: "https://sweethomejp.duckdns.org:9950"

# Loads default set of integrations. Do not remove.
default_config:

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards:
    # Main Dashboard
    lovelace-dashboard:
      mode: yaml
      title: Dashboard
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace/ui/dashboard.yaml

    # Rooms + Areas
    # lovelace-rooms:
    #   mode: yaml
    #   title: Rooms
    #   icon: mdi:sofa
    #   show_in_sidebar: true
    #   require_admin: false
    #   filename: lovelace/ui/rooms.yaml
