# Security View
# Made by Chettapong 2023
# https://hass-config.wipwup.xyz/
#
# Inspiration from Madelena Mak 2022
# https://mmak.es

title: Security
path: security

# visible:
#   - user: 7b356b6eaf634ffe8feb44cdb4a2c3d8
#   - user: 2d5a55df40354c07ac28bb75a217c2b8

type: "custom:grid-layout"
layout: !include ../shared/snippets/layout-page-margin.yaml

cards:
  - type: "custom:layout-card"
    layout_type: "custom:grid-layout"
    layout: !include ../shared/snippets/layout-page-columns.yaml
    view_layout:
      grid-area: cc
    cards:
      # [Header] Summary
      - type: "custom:layout-card"
        layout_type: "custom:grid-layout"
        layout: !include ../shared/snippets/layout-page-title-with-2-badges.yaml
        view_layout:
          grid-column: 1/-1
        cards:
          - type: markdown
            style: !include ../shared/snippets/style-markdown-page-title.yaml
            content: >
              # Security

              Front door is {{ iif(
              is_state('binary_sensor.front_door_contact_sensor_ias_zone',
              'on'), 'open', 'closed') }} and bathroom is {{ iif(
              is_state('binary_sensor.bathroom_leak_sensor_wet', 'on'),
              'wet', 'dry') }}.
      - type: custom:alarm-keypad-card
        title: DSCALARM_ESPHOME
        unique_id: dsc1
        disp_line1: sensor.dscalarm_line1
        disp_line2: sensor.dscalarm_line2
        service_type: esphome
        service: dscalarm_alarm_keypress_partition
        status_A: READY
        status_B: ARMED
        status_C: TROUBLE
        status_D: AC
        status_E: ""
        status_F: ""
        status_G: ""
        status_H: ""
        sensor_A: binary_sensor.dscalarm_partition_1_ready
        sensor_B: binary_sensor.dscalarm_partition_1_armed
        sensor_C: binary_sensor.dscalarm_trouble_status
        sensor_D: binary_sensor.dscalarm_ac_status
        sensor_E: ""
        sensor_F: ""
        sensor_G: ""
        sensor_H: ""
        button_A: STAY
        button_B: AWAY
        button_C: NIGHT
        button_D:
        button_E:
        button_F: <
        button_G: ">"
        button_H:
        cmd_A:
          keys: S
          partition: 1
        cmd_B:
          keys: W
          partition: 1
        cmd_C:
          keys: "N"
          partition: 1
        cmd_D:
          keys:
          partition: 1
        cmd_E:
          keys:
          partition: 1
        cmd_H:
          keys:
          partition: 1
        cmd_F:
          keys: <
          partition: 1
        cmd_G:
          keys: ">"
          partition: 1
        key_0:
          keys: "0"
          partition: 1
        key_1:
          keys: "1"
          partition: 1
        key_2:
          keys: "2"
          partition: 1
        key_3:
          keys: "3"
          partition: 1
        key_4:
          keys: "4"
          partition: 1
        key_5:
          keys: "5"
          partition: 1
        key_6:
          keys: "6"
          partition: 1
        key_7:
          keys: "7"
          partition: 1
        key_8:
          keys: "8"
          partition: 1
        key_9:
          keys: "9"
          partition: 1
        key_star:
          keys: "*"
          partition: 1
        key_pound:
          keys: "#"
          partition: 1
        text_1: BYPASS
        text_2: SERV
        text_3: ALARMS
        text_4: CHIME
        text_5: CODES
        text_6: FUNC
        text_7: OUTP
        text_8: PROG
        text_9: NIGHT
        text_star: SELECT
        text_pound: ENTER
        text_0: ""
        beep: sensor.dscalarm_beeps
        scale: 1
        view_pad: true
        view_display: true
        view_status: true
        view_status_2: false
        view_bottom: true
