substitutions:
  # change the name to suit your needs. This is what esphome will use as the friendly name for your component.
  # also used as a prefix for all fields
  device_name: "rgbic_cw_ww" # RGBCW Dream Color Strip Light
  wifi_ssid: !secret wifi_ssid # add in your esphome secrets file.
  wifi_password: !secret wifi_password # add in your esphome secrets file. -> per default this is also used for ota_password and web_password"

##### ESPHOME CONFIGURATION #####
esphome:
  name: $device_name
  friendly_name: rgbic_cw_ww

##### TYPE OF ESP BOARD #####
esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "U+2x7dV4ffHXIL0gogDNKhm5sEDoHI30t3am5bV0DgU="

##### OTA PASSWORD #####
ota:
  password: ${wifi_password}

##### WIFI SETUP #####
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: ${wifi_password}

captive_portal:

##### START - LIGHT CONFIGURATION #####
light:
  - platform: neopixelbus
    name: ${device_name} NeoPixel Light
    type: BRG
    variant: WS2811
    pin: GPIO00
    num_leds: 60

  - platform: cwww
    name: ${device_name} NeoPixel Light
    cold_white: output_component1
    warm_white: output_component2
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

##### START - OUTPUT CONFIGURATION #####
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: 2
    max_power: 100%
    
  - platform: esp8266_pwm
    id: output_component2
    pin: 3

##### START - TEXT SENSOR CONFIGURATION #####
text_sensor:
  ##### ESPhome version used to compile the app #####
  - name: ${device_name} ESPhome Version
    platform: version
    disabled_by_default: true

  - platform: wifi_info
    ip_address:
      name: ${device_name} IP
      disabled_by_default: true
      id: ip_address
    ssid:
      name: ${device_name} SSID
      disabled_by_default: true
    bssid:
      name: ${device_name} BSSID
      disabled_by_default: true

##### START - SENSOR CONFIGURATION #####
sensor:
  ##### WIFI Signal stregth
  - name: ${device_name} RSSI
    platform: wifi_signal
    update_interval: 60s