esphome:
  name: hvac-hitachi-ras-kh18clt
  friendly_name: HVAC Hitachi RAS-KH18CLT

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "atBZKoYwjcg+FvqNem6HqmTnjHltM/PfKzb5a+Lpxu0="

ota:
  password: "5fd91e95bc1098c488f66498c4acee05"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hvac-Hitachi-Ras-Kh18Clt"
    password: "UCKUjXV2hvOW"

captive_portal:
    